services:
  - type: static
    name: leo-ai
    env: static
    buildCommand: npm run build
    publishPath: ./build
    routes:
      - source: /assets/*
        destination: /assets/*
      - source: /*
        destination: /index.html
